apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura-graphql-engine
  labels:
    app: hasura
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hasura
  template:
    metadata:
      labels:
        app: hasura
    spec:
      containers:
        - name: hasura
          image: hasura/graphql-engine:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: hasura-config-secret
